# Deep Learning with TensorFlow 2.0 Tutorial - Building Your First ANN with TensorFlow 2.0

참고링크 : 
    https://github.com/laxmimerit/Building-Your-First-ANN-with-TensorFlow-2.0/blob/master/Deep%20Learning%20with%20TensorFlow%202.0%20Tutorial%20-%20Building%20Your%20First%20ANN%20with%20TensorFlow%202.0.ipynb
        

# 1. Defining the problem statement


In [2]:
# pip install tensorflow==2.0.0-rc0
# pip install tensorflow-gpu==2.0.0-rc0

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense

In [4]:
print(tf.__version__)

2.0.0


In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# 2. Collecting the data

In [7]:
dataset = pd.read_csv('Customer_Churn_Modelling.csv')

In [8]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
X = dataset.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = dataset['Exited']

In [10]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [11]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

# 3. Feature engineering

LabelEncoder 를 사용하면 문자열 그룹을 숫자열 그룹으로 간단히 변경할 수 있다.

In [12]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])
X.head()

In [14]:
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [15]:
label = LabelEncoder()
X['Gender'] = label.fit_transform(X['Gender'])
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [17]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

# 4. Feature Standardization

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [20]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [21]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

# 5. Build ANN

In [22]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [23]:
X.shape[1]

11

In [24]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [25]:
model.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 10, verbose = 1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 6s 736us/sample - loss: 0.4454 - accuracy: 0.8136
Epoch 2/10
8000/8000 [==============================] - 5s 564us/sample - loss: 0.3800 - accuracy: 0.8432
Epoch 3/10
8000/8000 [==============================] - 4s 513us/sample - loss: 0.3558 - accuracy: 0.8534
Epoch 4/10
8000/8000 [==============================] - 4s 441us/sample - loss: 0.3465 - accuracy: 0.8574
Epoch 5/10
8000/8000 [==============================] - 3s 436us/sample - loss: 0.3415 - accuracy: 0.8610
Epoch 6/10
8000/8000 [==============================] - 4s 557us/sample - loss: 0.3383 - accuracy: 0.8621
Epoch 7/10
8000/8000 [==============================] - 4s 552us/sample - loss: 0.3359 - accuracy: 0.8611
Epoch 8/10
8000/8000 [==============================] - 5s 677us/sample - loss: 0.3346 - accuracy: 0.8629
Epoch 9/10
8000/8000 [==============================] - 4s 561us/sample - loss: 0.3335 - accuracy: 0.8639
Epoch 10/10
8000/8000 [=

In [26]:
y_pred = model.predict_classes(X_test)

In [27]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [28]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [29]:
model.evaluate(X_test, y_test.to_numpy())

2000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.35134589195251464, 0.851]

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [31]:
confusion_matrix(y_test, y_pred)

array([[1509,   84],
       [ 214,  193]])

In [32]:
accuracy_score(y_test, y_pred)

0.851